# Generated by Django 4.0.3 on 2022-05-24 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('Order_data', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='kathmandu', max_length=100)),
                ('province', models.CharField(default='Bagmati', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('M', 'mother'), ('B', 'baby')], default=None, max_length=20)),
                ('product_nature_mother', models.CharField(choices=[('PE', 'pregancy_essential'), ('Cl', 'clothing'), ('B', 'beauty'), ('J', 'jewllery'), ('WN', 'willness'), ('PC', 'Podcast')], default=None, max_length=20)),
                ('product_nature_baby', models.CharField(choices=[('NBE', 'new_born_essential'), ('TD', 'toddlers'), ('BS', 'bestseller'), ('FW', 'footwear'), ('KC', 'kidscare'), ('KF', 'kidsfedding')], default=None, max_length=20)),
                ('baby_gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], default=None, max_length=10)),
                ('Name', models.CharField(blank=True, max_length=100)),
                ('product_color_blue', models.ImageField(blank=True, upload_to='media')),
                ('product_color_orange', models.ImageField(blank=True, upload_to='media')),
                ('product_color_green', models.ImageField(blank=True, upload_to='media')),
                ('product_color_pink', models.ImageField(blank=True, upload_to='media')),
                ('product_color_yellow', models.ImageField(blank=True, upload_to='media')),
                ('product_size', models.CharField(choices=[('XL', 'Extra_Large'), ('L', 'Large'), ('M', 'Medium'), ('S', 'Small'), ('XS', 'XtraSmall')], default='M', max_length=20)),
                ('Price', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('vendor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.profilevendor')),
            ],
        ),
        migrations.CreateModel(
            name='OrderIteamCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product_coloring', models.CharField(choices=[('Gr', 'green'), ('R', 'red'), ('B', 'blue'), ('P', 'pink'), ('Y', 'yellow')], max_length=20)),
                ('product_sizing', models.CharField(choices=[('XL', 'Extra_Large'), ('L', 'Large'), ('M', 'Medium'), ('S', 'Small'), ('XS', 'XtraSmall')], max_length=20)),
                ('carted', models.BooleanField(default=False)),
                ('Carted_data', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.ordercustomer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.product')),
            ],
        ),
        migrations.AddField(
            model_name='ordercustomer',
            name='vendor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.profilevendor'),
        ),
    ]
