# Generated by Django 4.0.3 on 2022-05-24 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderiteamcustomer',
            old_name='Carted_data',
            new_name='Carted_date',
        ),
    ]
