# Generated by Django 4.0.3 on 2022-05-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_remove_ordercustomer_vendor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderiteamcustomer',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
