# Generated by Django 4.0.3 on 2022-05-24 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_alter_orderiteamcustomer_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderiteamcustomer',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.product'),
        ),
    ]
