# Generated by Django 4.0.3 on 2022-05-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_alter_orderiteamcustomer_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderiteamcustomer',
            name='product_coloring',
        ),
        migrations.AddField(
            model_name='orderiteamcustomer',
            name='selected_image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
